server:
  port: 8001



spring:
  application:
    name: mod-app-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://db_mysql:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoyutech.mall.app.entities